# travis config

language: r

sudo: required

r_github_packages:
  - jimhester/robustr
  - jimhester/covr
  - hadley/testthat

after_success:
  - Rscript -e 'library(covr);coveralls(quiet = FALSE);codecov()'

notifications:
  email:
    recipients:
        - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
