# travis config, based on https://github.com/craigcitro/r-travis

language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_packages:
  - covr

r_github_packages:
  - mllg/checkmate
  - hadley/testthat

after_success:
  - Rscript -e 'Sys.setenv(R_EXPENSIVE_TEST_OK="true");library(covr);coveralls()'
  - Rscript -e 'Sys.setenv(R_EXPENSIVE_TEST_OK="true");library(covr);codecov()'

notifications:
  email:
    recipients:
      - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
