# travis config, based on https://github.com/craigcitro/r-travis

language: r

sudo: required

r_github_packages:
  - jimhester/robustr
  - jimhester/covr
  - hadley/testthat
  
after_success:
  - travis_wait Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
        - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
