# travis config, based on https://github.com/craigcitro/r-travis

language: c

env:
   global:
     - _R_CHECK_TIMINGS_=0

branches:
  only:
   - master

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh aptget_install r-cran-rjava
  - sudo R CMD javareconf
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh install_deps


script: travis_wait ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs


notifications:
  email:
    recipients:
        - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
