# travis config, based on https://github.com/craigcitro/r-travis

language: r
sudo: false
cache: packages

r:
  - release
  - devel

#r_packages:
#  - covr
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    recipients:
      - kerschke@uni-muenster.de
    on_success: change
    on_failure: always
